// http://download.ufactory.cc/docs/en/uArm%20Swift%20Pro_Developer%20Guide%20v1.0.6.pdf
module.exports = {
  LOG_LEVEL: 1,

  // Types
  MESSAGE_GCODE_SEND_PREFIX: "#",
  MESSAGE_GCODE_RECEIVE_PREFIX: "$",
  MESSAGE_TICKING_FEEDBACK_PREFIX: "@",
  MESSAGE_ERROR_PREFIX: "E",

  RECEIVE_REGEXP: new RegExp(/^(refer:|E|\$|@)(\d+)*\s+(.+)*/),
  SPEED_DEFAULT: 500,

  // Modes
  CARTESIAN_MODE: 1,
  POLAR_MODE: 2,

  // MESSAGE_TICKING_FEEDBACK_PREFIX
  TICKING_UARM_READY: 1,
  TICKING_UARM_TIMED_FEEDBACK: 3,
  TICKING_UARM_BUTTON_EVENT: 4,
  TICKING_UARM_POWER_SUPPLY: 5,
  TICKING_UARM_LIMIT_SWITCH_EVENT: 6,
  TICKING_UARM_TEMP_ERROR: 7,
  TICKING_UARM_STOP_MOVEMENT: 9,

  // Errors
  ERROR_COMMAND_NOT_EXIST: 20,
  ERROR_PARAMETER_ERRORS: 21,
  ERROR_OUT_OF_RANGE: 22,
  ERROR_BUFFER_FULL: 23,
  ERROR_POWER_LOSS: 24,
  ERROR_OPERATION_FAILURE: 25,
}
