// http://download.ufactory.cc/docs/en/uArm%20Swift%20Pro_Developer%20Guide%20v1.0.6.pdf
module.exports = {
  LOG_LEVEL: 1,

  // Types
  MESSAGE_GCODE_SEND_PREFIX: "#",
  MESSAGE_GCODE_RECEIVE_PREFIX: "$",
  MESSAGE_TICKING_FEEDBACK_PREFIX: "@",
  MESSAGE_ERROR_PREFIX: "E",

  SPEED_DEFAULT: 500, // mm/min

  // Coordinate modes
  CARTESIAN_MODE: 1,
  POLAR_MODE: 2,

  // uArm modes
  MODES: {
    NORMAL: 0,
    LASER: 1,
    PRINTING_3D: 2,
    UNIVERSAL_HOLDER: 3,
  },

  // Servos / motors
  SERVO_BOTTOM: 0,
  SERVO_LEFT: 1,
  SERVO_RIGHT: 2,
  SERVO_HAND: 3,

  // MESSAGE_TICKING_FEEDBACK_PREFIX
  TICKING_UARM_READY: 1,
  TICKING_UARM_TIMED_FEEDBACK: 3,
  TICKING_UARM_BUTTON_EVENT: 4,
  TICKING_UARM_POWER_SUPPLY: 5,
  TICKING_UARM_LIMIT_SWITCH_EVENT: 6,
  TICKING_UARM_TEMP_ERROR: 7,
  TICKING_UARM_STOP_MOVEMENT: 9,

  // Errors
  ERROR_COMMAND_NOT_EXIST: 20,
  ERROR_PARAMETER_ERRORS: 21,
  ERROR_OUT_OF_RANGE: 22,
  ERROR_BUFFER_FULL: 23,
  ERROR_POWER_LOSS: 24,
  ERROR_OPERATION_FAILURE: 25,
}
